POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvYmkxMjNAdGVzdC5jb20iLCJleHAiOjE3NDU2MTM5NjQsInVzZXJJZCI6MX0.Y8SIZrjA2p70k8WNt8RskjNkOglzSX8rCed1fF0Li80

{
    "title": "Test event",
    "description": "test description for test event",
    "location": "Test event location",
    "dateTime": "2025-04-13T20:25:00.000Z"
}